language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
  features: [
              ["low", "title", "upper"],
              ["bias", "upper", "title", "digit", "pattern"],
              ["low", "title", "upper"]
            ]
